### ISSUE TITLE
[Feature Request] Wrapping this repo into Cython

### ISSUE THREAD

**Issue by guikarist** [m2q/pomcpp#4]
Thanks for implementing and maintaining this excellent repo!

However, I find that I must implement my agent in C++ by using your repo. And I cannot use a [docker agent](https://github.com/MultiAgentLearning/playground/tree/master/docs#using-a-docker-agent) either.

There is already a [Cython implementation](https://github.com/tambetm/pommerman-baselines/tree/master/cython_env) which you may have a look at.

**Comment by m2q** [comment]
Hi, thanks!

I am actively maintaining this repo (and will do so for the rest of this year at least, don't worry). The forward model matches pommerman exactly (I unit tested it).

Currently, only FFA is implemented. Since I'm using this repo for my own agent as well, I will definitely need a working docker agent soon, to be able to test against other competitors. 

- [ ] Docker
- [ ] Partial Observations
- [ ] anything else

**Comment by guikarist** [comment]
So my agent should be implemented in C++, right?

If so, I must use C++ version of Pytorch or Tensorflow.

**Comment by guikarist** [comment]
It now takes me **two days** for me to train a a2c agent using original playground, which is really frustrating.

**Comment by m2q** [comment]
Yes, I'm currently using libtorch (which is the C++ version of pytorch). The API of libtorch is almost identical to the python one, so you really don't have to learn much new stuff. 

Now: I don't really know where your bottleneck is, so I can't promise any major performance improvements. The only thing I can say is that this implementation will give you incredible simulation speed and also uses 0 heap memory. Also doing funky parallelization will be easier than with python.
